language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3

before_install:
  - curl https://dist.crystal-lang.org/apt/setup.sh | sudo bash
  - sudo apt-get -qq update
  - sudo apt-get install -y crystal

before_script:
  - cd ext/fast_inflector && make
  - cp fast_inflector.bundle ../../lib/fast_inflector/fast_inflector.bundle
